kind = "web"
previewPath = "/"
title = "Arpit Thrift"
version = "1.0.0"
id = "artifacts/arpit-thrift"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19378

[services.development]
run = "pnpm --filter @workspace/arpit-thrift run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/arpit-thrift", "run", "build" ]
publicDir = "artifacts/arpit-thrift/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19378"
BASE_PATH = "/"
